name: Build and Test "main_component" Component

on:
  push:
    branches:
      - master
      - main
      - develop
      - feature
      - refactor
  pull_request:
    branches:
      - master
      - main
      - develop

jobs:
  build_and_test:
    name: Build the source code and run Tests(GoogleTest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code 
        uses: actions/checkout@v3
      - name: Install prerequisites  
        run: sudo apt-get install -y cmake build-essential