name: "build and run the project_x"

on:
  push:
    branches:
      - master
      - main
      - develop
      - feature
      - refactor
  pull_request:
    branches:
      - master
      - main
      - develop
jobs:
  build_and_test:
    name: Build the project_x code and run the code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code 
        uses: actions/checkout@v3
      - name: Install prerequisites  
        run: sudo apt-get install -y python3 python3-pip cmake build-essential tree
      - name: visual code check 
        run: |
          tree .
      - name: build the code
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
      - name: notify user
        run: echo "Success!"